name: Deploy NextJs application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t zkzkrgn/next-js-ec2 .

      - name: Login to Docker Hub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Publish image to Docker Hub
        run: docker push zkzkrgn/next-js-ec2:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull zkzkrgn/next-js-ec2:latest

      - name: Delete old container
        run:  docker rm -rf nextjsAppContainer
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name nextjsAppContainer zkzkrgn/next-js-ec2:latest
